class SensorType:
    """Enumeration of sensor types for each machine type."""
    
    # Temperature sensors
    RTD_PT100 = "RTD_PT100"
    THERMOCOUPLE_K_TYPE = "THERMOCOUPLE_K_TYPE"
    THERMOCOUPLE_J_TYPE = "THERMOCOUPLE_J_TYPE"
    INFRARED_TEMP = "INFRARED_TEMP"
    THERMISTOR = "THERMISTOR"
    BIMETALLIC_TEMP_SWITCH = "BIMETALLIC_TEMP_SWITCH"
    THERMAL_IMAGING = "THERMAL_IMAGING"
    
    # Vibration/motion sensors
    PIEZOELECTRIC_ACCELEROMETER = "PIEZOELECTRIC_ACCELEROMETER"
    ROTARY_ENCODER = "ROTARY_ENCODER"
    GYROSCOPE = "GYROSCOPE"
    MEMS_ACCELEROMETER = "MEMS_ACCELEROMETER"
    PROXIMITY_PROBE = "PROXIMITY_PROBE"
    STRAIN_GAUGE = "STRAIN_GAUGE"
    INDUSTRIAL_ACCELEROMETER = "INDUSTRIAL_ACCELEROMETER"
    VELOCITY_SENSOR = "VELOCITY_SENSOR"
    
    # Audio sensors
    INDUSTRIAL_MICROPHONE = "INDUSTRIAL_MICROPHONE"
    ACOUSTIC_EMISSION = "ACOUSTIC_EMISSION"
    
    # Level sensors
    CAPACITIVE_LEVEL = "CAPACITIVE_LEVEL"
    ULTRASONIC_LEVEL = "ULTRASONIC_LEVEL"
    FLOAT_LEVEL_SWITCH = "FLOAT_LEVEL_SWITCH"
    RADAR_LEVEL = "RADAR_LEVEL"
    HYDROSTATIC_LEVEL = "HYDROSTATIC_LEVEL"
    
    # Power/electrical sensors
    CURRENT_TRANSFORMER = "CURRENT_TRANSFORMER"
    POWER_METER = "POWER_METER"
    
    # Position/distance sensors
    LINEAR_ENCODER = "LINEAR_ENCODER"
    ABSOLUTE_ENCODER = "ABSOLUTE_ENCODER"
    LVDT = "LVDT"
    MAGNETOSTRICTIVE_POSITION = "MAGNETOSTRICTIVE_POSITION"
    LIMIT_SWITCH = "LIMIT_SWITCH"
    LASER_DISTANCE = "LASER_DISTANCE"
    PHOTOELECTRIC = "PHOTOELECTRIC"
    
    # Pressure/flow sensors
    PRESSURE_TRANSDUCER = "PRESSURE_TRANSDUCER"
    ELECTROMAGNETIC_FLOW = "ELECTROMAGNETIC_FLOW"
    DIFFERENTIAL_PRESSURE = "DIFFERENTIAL_PRESSURE"
    STRAIN_GAUGE_PRESSURE = "STRAIN_GAUGE_PRESSURE"
    PIEZOELECTRIC_PRESSURE = "PIEZOELECTRIC_PRESSURE"
    BOURDON_TUBE_GAUGE = "BOURDON_TUBE_GAUGE"
    BOURDON_PRESSURE_GAUGE = "BOURDON_PRESSURE_GAUGE"
    DIAPHRAGM_PRESSURE = "DIAPHRAGM_PRESSURE"
    TURBINE_FLOW = "TURBINE_FLOW"
    ULTRASONIC_FLOW = "ULTRASONIC_FLOW"
    
    # Force/load sensors
    LOAD_CELL = "LOAD_CELL"
    PIEZOELECTRIC_FORCE = "PIEZOELECTRIC_FORCE"
    BELT_SCALE_LOAD_CELL = "BELT_SCALE_LOAD_CELL"
    
    # Speed sensors
    TACHOMETER = "TACHOMETER"
    HALL_EFFECT = "HALL_EFFECT"
    INCREMENTAL_ENCODER = "INCREMENTAL_ENCODER"
    
    # Detection sensors
    INDUCTIVE_PROXIMITY = "INDUCTIVE_PROXIMITY"
    LASER_SCANNER = "LASER_SCANNER"
    ULTRASONIC_SENSOR = "ULTRASONIC_SENSOR"
    
    # Safety sensors
    EMERGENCY_STOP = "EMERGENCY_STOP"
    LIGHT_CURTAIN = "LIGHT_CURTAIN"
    SAFETY_MAT = "SAFETY_MAT" 